### ISSUE TITLE
Unmet python dependencies (scipy and matplotlib)

### ISSUE THREAD

**Issue by DavidKi** [ISAAKiel/profileAAR#14]
I am using QGIS 3.4 (LTR) on Ubuntu 18.04 (LTR). When installing profileAAR, it could not be loaded, due to missing modules: "ModuleNotFoundError: No module named 'scipy'"

Manually installing it, **didn't** help: `sudo apt-get install python-scipy` and `pip install scipy`

Probably this is because, you support only QGIS 3.6?

Would it be possible to support the LTR as well? The 3.4 LTR will be available until February 2020 (https://www.qgis.org/de/site/getinvolved/development/roadmap.html). Only then it will be updated to 3.10.

**Comment by MartinHinz** [comment]
Tried it with 3.6, same problem, additionally dependency is also matplotlib. Manual installation helped in my case.

Using Arch:

`sudo pacman -S python-scipy python-matplotlib`

**Comment by DavidKi** [comment]
I have tried it on another machine (Ubuntu 18.04) with QGIS 3.6 and manual installation of matplotlib and scipy. In my case without success.
In case the complete error message is helpful:
```

Couldn't load plugin 'profileAAR' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'scipy' 
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profileAAR/__init__.py", line 34, in classFactory
    from .profileAAR import profileAAR
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profileAAR/profileAAR.py", line 71, in 
    from .transformation import sectionCalc
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profileAAR/transformation.py", line 63, in 
    import scipy
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'

Python version: 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c 
```

**Comment by DavidKi** [comment]
@nevrome pointed me to the solution: I had manually installed the wrong version of scipy. With `sudo apt-get install python3-scipy` the manuall installation worked. Nevertheless the dependency should be fixed, so user has no need to install anything manually.
