### ISSUE TITLE
python-error

### ISSUE THREAD

**Issue by JackieEid** [ISAAKiel/profileAAR#15]
Hi guys, 
am a german archaeologist who is clueless about python/ coding but uses QGIS. Would love to try out profileAAR, seems to be exactely what I need, but it does not work:

_2021-03-02T11:41:25     WARNING    Traceback (most recent call last):
File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profileAAR\profileAAR.py", line 593, in run sys.exitfunc()
AttributeError: module 'sys' has no attribute 'exitfunc'_

Can anybody help?

**Comment by nmueller18** [comment]
Thank you for your interest! Could you please give a little more context about your system (OS, Python, QGIS versions)?

**Comment by MoritzMennenga** [comment]
Hello,
can you please send some more informations: QGIS-Version, operating system. And does the error appears while installing or using it?

**Comment by JackieEid** [comment]
wow, fast!
Windows 10, QGIS 3.16.1 (no clue about the python version, sorry...)
appears while trying to use it.

found another error warning:
_The z-Value needs to be a float. Check the field type of the z-Value_

after transforming the height values to something that fits the float description I got a result!!! 
but also another Python warning:

_C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profileAAR\export.py:101: DeprecationWarning: QgsVectorFileWriter constructor is deprecated writer = QgsVectorFileWriter(filename, "utf-8", export_fields, QgsWkbTypes.Point, corrdinate_system, "ESRI Shapefile")
traceback: File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profileAAR\profileAAR.py", line 529, in run result = self.dlg.exec_()
File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profileAAR\profileAAR.py", line 759, in run
export.export(coord_trans, self.dlg.outputPath.text(), selectedLayer.crs())
File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profileAAR\export.py", line 101, in export
writer = QgsVectorFileWriter(filename, "utf-8", export_fields, QgsWkbTypes.Point, corrdinate_system, "ESRI Shapefile")_

**Comment by MoritzMennenga** [comment]
It would be perfect, if you could attach an example of your data that is not working

**Comment by JackieEid** [comment]
[FG-Punkte.zip](https://github.com/ISAAKiel/profileAAR/files/6068618/FG-Punkte.zip)
the shape-file with my FG-measurements.

I am trying to straighten out a profile foto. with these measurements.
To rectify a vertical image I would usually get said picture and a drawing with measured distances between the fotogrammetry-nails, use these as "coordinates" and then simply pretend it is a horizontal image and georeference it accordingly. But I have no measurements this time. 
(workflow is not necessarily scientific and the result is not georeferenced correctly, but it works nicely if you just want to straighten out the picture of some profile.)

**Comment by MoritzMennenga** [comment]
Ok, with the z-value as float it works in my case. Most of the warnings " QgsVectorFileWriter constructor is deprecated" have no effect on the results.
But be careful with your points, because the profile is not in a line. There is a "  DISTANCE WARNING!", that says, that the result is not accurate. This is the result of a bent profile or errors in the points.

**Comment by JackieEid** [comment]
thanks for the warning! 
(and all your quick responses!!!)

I noticed the points beeing a bit off, but it is all I got... -.-

**Comment by MoritzMennenga** [comment]
Sometimes it works better, if you split the profiles, if they are very long or not straight. Unfortunately the possibility to merge these parts is not implemented, therefore you have to do it by hand
