### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by archaeofx** [ISAAKiel/profileAAR#17]
When I try to use the profilAAR plugin, QGIS returns this error:

AttributeError: module 'sys' has no attribute 'exitfunc' 
Traceback (most recent call last):
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profileAAR/profileAAR.py", line 593, in run
    sys.exitfunc()
AttributeError: module 'sys' has no attribute 'exitfunc'

I tried to google it and as far as I understand the _sys.exitfunc()_  is deprecated since version 2.4 of Python and apparently was removed in Python 3. Is this a known issue?

**Comment by MoritzMennenga** [comment]
Can you please give us some information about your operating system, the QGIS version and the profileAAR version?

**Comment by archaeofx** [comment]
Thanks for the quick reply!

I'm using QGIS 3.22.4 Białowieża with profileAAR version 2.0.2  on Ubuntu 22.04

**Comment by MoritzMennenga** [comment]
Ok, I think I renewed all depricated classes in the github version. Maybe you can download the latest version from git and test it, because I can't build your setup here at the moment (on windows it is only a warning)
I will check it in the next days and push it to the qgis plugin library
