### ISSUE TITLE
Translate from archprofile (R) to python

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/profileAAR#2]

**Comment by kschmuetz** [comment]
Hi Moritz,

I will try to find some time to look at the qgis documentation and see how they build their plugins. Once I have something done I´ll send you a mail or post it here.

All the best,
Kay

**Comment by bserbe** [comment]
Hello everyone,
due to my master thesis I recently faced the QGIS API. Information regarding the use of the API and scripting of plug-ins I recommend this Introduction:
http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/index.html
And the API Documentation:
https://qgis.org/api/

Regards
Benni

P.S. As soon as my thesis is submitted I am free to work at ISAAK projects again

**Comment by MoritzMennenga** [comment]
I started with the GUI now, and maybe the next days I try to figure out mor how python works
@bserbe thanks for the links

**Comment by kschmuetz** [comment]
@bserbe Thanks for the links they make a quite good introduction
I followed the tutorial here http://www.qgistutorials.com/de/docs/building_a_python_plugin.html to build a litte plugin. I had some little tweaks to do here and there but got it running. 
To my understanding the plugins in qgis are developed as classes (so a little bit of object oriented programming happening there, which is something I rarely do but fortuenatly the plugin used in the tutorial does most of the work). The good thing is that the actual task of the plugin runs in the run method so that it´s more or less just a script that has to be developed from your algorithm now. I'll try and have a look at that over the weekend.
All the best,
Kay

**Comment by MoritzMennenga** [comment]
Maybe you can clone the repo of the Python plugin, so that we can work on the same thing parallel.

**Comment by MoritzMennenga** [comment]
I uploaded a dataset with testdata and the result

**Comment by preiaen** [comment]
Hey all, I'm willing to contribute to the GUI development but have some questions.

@MoritzMennenga do you have some sort of project description? I browsed the isaak repo, but couldn't find one. As far as I understood the project, the main algorithm, who gets the job done, is already working, whats missing is a GUI for QGIS. The GUI should request some input data from the user and pass it to the allready working algorithm. After it is finished with his magic it will return some sort of data, which either ends in the users filesystem or is presented to him in some other way. Is that correct so far? Is there a interface description what data comes in and out of the algorithm? Is there a sketch somewhere how the gui should look like? How much error handling do we need to develop, or is  qgis responsible for that? Probably not. If you could describe shortly what the plugin should be capable of or point me to such an description, that would be very helpful for me to understand how much work is to be done here.

**Comment by MoritzMennenga** [comment]
@preiaen Is this Nils?
in short words. I made a script in R which transforms fotogrammetric profil control points (Fotogrammetrienägel aus Profilen), so that it is possible to rectify the images with the qgis referencer. You will find the way I do it and the options [here](https://github.com/ISAAKiel/recexcavAAR/blob/archProfile/vignettes/archProfile_vignette_en.pdf)
The in and output and the gui is quite simple, because the QGIS plugin builder handle these problems for us. If you clone the repository to your QGIS Plugin Folder (windows in most cases: C:\User\XXX\.qgis2\python\plugins\) The plugin is in QGIS, when you start it (the icon is a yellow plug at the moment) There you can see the GUI (and my first steps in python).
There is a "errorhandling"... you will get a python error if there is something wrong. But it would be nice, if we can check the data in the beginning (is there only N,E,S,W in the view column; are ther only floats in the z column....), maybe we can start a new issue for that.
There is the idea, that @kschmuetz and me are meeting via skype in the next week and discuss all the details and check how hard it will be to translate it. Maybe you like to join? But I think it can't be so hard, because the steps behind it are really simple.
![profilaar](https://user-images.githubusercontent.com/17044206/30168629-48496182-93ea-11e7-9dc4-a049ee58af91.jpg)

**Comment by preiaen** [comment]
Yes its Nils II. :) Okay a skype meeting next week sounds good. My skype handle is also preiaen. Until then I'll check out your good and have a look into it.

**Comment by MoritzMennenga** [comment]
@kschmuetz Maybe, we can discuss a time here.
@preiaen Are you in Kiel next week?

**Comment by preiaen** [comment]
Yes I will be in Kiel next week.

**Comment by MoritzMennenga** [comment]
Ok, then there is the possibility for a physical meeting with Kay, too.

**Comment by kschmuetz** [comment]
Hi @preiaen and @MoritzMennenga ,
Monday and Tuesday would both work for me (my other appointments can all be rearranged). We can meet in my office at the Graduate School for example, we should have some peace and quiet there ;)
What do you think about 11am on Monday?

**Comment by MoritzMennenga** [comment]
That would be perfect for me

**Comment by preiaen** [comment]
11am Monday isn't that good for me, what about tuesday same time.

**Comment by kschmuetz** [comment]
11am Tuesday works for me.

**Comment by MoritzMennenga** [comment]
for me, too. But I have to leave at 11:55 am.

**Comment by preiaen** [comment]
Kay would you give me the room number and building, I have to go to. I recognized now that I didn't have these informations :-)

**Comment by kschmuetz** [comment]
I am in the Leibnitzstr. 3 on the first floor in room 124 (one of the corner offices)

**Comment by MoritzMennenga** [comment]
Hey @preiaen and @kschmuetz have you talked about further things, or do we discuss the rest on thursday (is there a meeting?)? Do you have a plan?

**Comment by kschmuetz** [comment]
Hi Moritz, 
I hope everything went well. There shouldn´t be an official meeting on thursday (I think...), but we thought we might have a little get together in the afternoon via skype again. I am not sure if I´ll be able to get something done before that. Would thursday afternoon suite you aswell?

**Comment by MoritzMennenga** [comment]
Yes, Thursday is fine!

**Comment by MoritzMennenga** [comment]
Is there a time, we will meet?

**Comment by kschmuetz** [comment]
I would suggest 14:30?

**Comment by MoritzMennenga** [comment]
It's fine for me

**Comment by preiaen** [comment]
I'm working from home and can join you via Skype if thats okay? I'm currently refactoring the code, and try to get most of it in classes and functions.

**Comment by MoritzMennenga** [comment]
Sounds good

**Comment by MoritzMennenga** [comment]
Our internet in the institute chrashed today. I will make the changings with the errorhandling tomorrow.

**Comment by MoritzMennenga** [comment]
The layerselection works now. It displays only vector point layers. The check if the crs is correct will be done after pressing run
Kay translated the rest of the code and implemented the QgsMapLayerComboBox, thats why it works now.
I would place the icon in the gui, but it does not work with the qt as it should. Next steps would be:
- Checking the accuracy with a standard profile (Moritz next week)
- Writing the paper (I will start and send it to you)
- Checking the code (@preiaen)
- Calculating the error with residuals? #7 
- Checking if the points are in logical distances (@crinne)
- Splitting the profile in parts #6 (Maybe we have to dicuss that via skype)
- Very important: Doing the things we need for the release #8
