### ISSUE TITLE
Increasing the accuracy

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/profileAAR#6]
The problems with long profiles, like the ones of the trenches, is, that they have the high probability to be not very straight. This causes in a high inaccuracy. Th solve this problem, there is the idea to split long profiles automatic in short profiles. We can compare the z-values of points with nearly the same x and y coordinates, if we have more than twice comparable points with points in between, we can split the profile, rotate them and merge the profiles afterwards.

**Comment by kschmuetz** [comment]
Idea from Skype brainstorming session:
- let the user manually select the different parts of his profile, calculate them seperately and merge afterwards (https://gis.stackexchange.com/questions/84516/qgis-2-0-plugin-select-and-identify-a-single-feature)

**Comment by MoritzMennenga** [comment]
something like that is implemented.
