### ISSUE TITLE
Calculating Residuals

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/profileAAR#7]
To get a better understanding for the accuracy of the data it would be nice to calculate the residuals of each point and calculate the min max and mean for the profile.
Is there a easy way to predict not using sklearn or pandas?

**Comment by MoritzMennenga** [comment]
I pushed a try to calculate the residuals, but there is a problem.
Because there is no predict in standart python i generated the predivction myself:

`intercept + rvalue * xw[k]`
intercept = konstates Glied
rvalue = regressionskoeffizient
xw[k] der jeweilige x wert
the result has to be the estimated y

then I subtracted the real y value
`yw[k] - (intercept + rvalue * xw[k])`
this has to be the residual
But I got 

> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	0
> 2017-09-20T12:43:09	1	0.00416439805258
> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	-0.402944200841
> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	-0.179866436519
> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	3
> 2017-09-20T12:43:09	1	-0.00293495407649
> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	4
> 2017-09-20T12:43:09	1	-0.414142315475
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	0
> 2017-09-20T12:43:09	1	-0.226537433721
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	1
> 2017-09-20T12:43:09	1	0.627642041284
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	-0.139045362513
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	3
> 2017-09-20T12:43:09	1	-0.232596830436
> 2017-09-20T12:43:09	1	2
> 2017-09-20T12:43:09	1	4
> 2017-09-20T12:43:09	1	-0.0135912077975
> 2017-09-20T12:31:31	1	0.232596830436
> 2017-09-20T12:31:31	1	2
> 2017-09-20T12:31:31	1	4
> 2017-09-20T12:31:31	1	0.0135912077975

Results estimated (R):

> PROFILE [1] "1"
>            1            2            3            4            5 
>  0.004164398  0.005360811 -0.003395106 -0.002259054 -0.003871049 
> PROFILE [1] "2"
>           1           2           3           4           5 
> -0.22653743  0.62625640 -0.14339709 -0.23261350 -0.02370838 

The first values are correct but the rest is wrong


`    def linreg_residuals (self, linegress, xw, yw, prnumber):
        #calculate the residuals for each point and add the as an Attribute
        intercept = linegress[1]
        rvalue = linegress[2]
        for k in range(len(xw)):
            QgsMessageLog.logMessage(str(prnumber), 'MyPlugin')
            QgsMessageLog.logMessage(str(k), 'MyPlugin')
            QgsMessageLog.logMessage(str(yw[k] - (intercept + rvalue * xw[k])), 'MyPlugin')`

Has anyone an idea??

The dataset is Test_residuals. Profile 1 is ok, Profile 2 is rubbish

**Comment by kschmuetz** [comment]
xw and yw are not the "pure" coordinates but processed with "x_coord_proc[x] - min(x_coord_proc)".
Maybe there is the error... try using x_coord_proc for the real x-values etc.

**Comment by MoritzMennenga** [comment]
I don't think, that this si the problem, because it doesn't matter if I use xw/yw or coord_proc, bechause the residuals have to be the same.
I think it is an mathematical problem caused by me ;-)

I used the same data in R:

![pr2_regression-01](https://user-images.githubusercontent.com/17044206/30645664-b3bfa666-9e16-11e7-9195-e337d41c9826.jpg)

**Comment by MoritzMennenga** [comment]
Solved! muss nicht rvalue, sondern solpe in rad sein

**Comment by MoritzMennenga** [comment]
The residuals will be calculated.
At the moment the result will be added to the prompt.
I would like to have an ScrollArea to append the text in. But I cannot change the gui, because it causes errors. Maybe @kschmuetz can fix it

**Comment by kschmuetz** [comment]
Hi I already posted this in the errorhandling section, but it could help here aswell. I hope this is the error you are talking about?

"Due to the addition of the QgsMapLayerComboBox there is an error that occurs if the gui is changed. The error message is something like: Can´t import qgsmaplayercombobox.h.
To get it running again go to the *.ui-file and look for:
\<class\>QgsMapLayerComboBox\<\/class\>
\<extends\>QComboBox\<\/extends\>
\<header\>qgsmaplayercombobox.h\<\/header\>
Change "qgsmaplayercombobox.h" in the last line to "qgis.gui" and save the file.
That should fix that problem."

**Comment by MoritzMennenga** [comment]
This is the error:

> 2017-09-20T17:14:26	1	Traceback (most recent call last):
> 			  File "D:/Program Files/QGIS 2.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
> 			    plugins[packageName] = package.classFactory(iface)
> 			  File "C:/Users/mo1005.NIHK/.qgis2/python/plugins\profileAAR\__init__.py", line 34, in classFactory
> 			    from .profileAAR import profileAAR
> 			  File "D:/Program Files/QGIS 2.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			  File "C:/Users/mo1005.NIHK/.qgis2/python/plugins\profileAAR\profileAAR.py", line 43, in <module>
> 			    from profileAAR_dialog import profileAARDialog
> 			  File "D:/Program Files/QGIS 2.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			  File "C:/Users/mo1005.NIHK/.qgis2/python/plugins\profileAAR\profileAAR_dialog.py", line 29, in <module>
> 			    os.path.dirname(__file__), 'profileAAR_dialog_base.ui'))
> 			  File "D:\Program Files\QGIS 2.18\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
> 			    exec(code_string.getvalue(), ui_globals)
> 			  File "<string>", line 118, in <module>
> 			  File "D:/Program Files/QGIS 2.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
> 			    mod = _builtin_import(name, globals, locals, fromlist, level)
> 			ImportError: No module named resources_rc
>

**Comment by kschmuetz** [comment]
OK the same file (*.ui)
find:
  \<resources\>
  \<include location\=\"resources.qrc\"\/\>
  \<\/resources\>
and replace the hole thing with:
  \<resources\/\>
Save the file and it should work...
https://gis.stackexchange.com/questions/139625/qgis-plugin-problems-importing-resources-resources-rc-file-plugin-doesnt-l

**Comment by MoritzMennenga** [comment]
seems to work

**Comment by MoritzMennenga** [comment]
perfect, thanks.
next question is, where do I change the code, that the GUI do not close after executing. 
Google inforamtions are really rare

**Comment by MoritzMennenga** [comment]
found something

**Comment by kschmuetz** [comment]
First promising thing I found was:
https://gis.stackexchange.com/questions/186295/plugin-development-ignore-close-event

**Comment by MoritzMennenga** [comment]
I think the log is also very well placed in the MessageLog

**Comment by MoritzMennenga** [comment]
ok, I saw a big problem with this way to do it. I added a plot to schow it. I will give a call tomorrow

**Comment by MoritzMennenga** [comment]
Fixed in a total differend way
